### ISSUE TITLE
Fails to boot, for java version 1.8.0_121, Maven 3.5.0, Node v8.3.0, angular-cli: 1.3.0

### ISSUE THREAD

**Issue by paul-hammant** [protubero/angular-jooby-starter#1]
>>> jooby:run[error|HotSwap]: de.protubero.ajs.App.start() resulted in error
java.lang.LinkageError: Failed to link org/jooby/internal/run__/JoobyRef (Module "de.protubero.ajs-root:main" from AppModuleLoader@3af57c4c for finders [])
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
	at org.jboss.modules.Module.loadModuleClass(Module.java:560)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.jooby.run.Main.lambda$startApp$1(Main.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: javaslang/control/Try$CheckedConsumer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
	... 14 more
Caused by: java.lang.ClassNotFoundException: javaslang.control.Try$CheckedConsumer from [Module "de.protubero.ajs-root:main" from AppModuleLoader@3af57c4c for finders []]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)

**Comment by paul-hammant** [comment]
This could be because I did `jooby:run` in the root folder.  When I changed directories, it did not happen.
